# Generated by Django 5.2.3 on 2025-07-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
